name: NavOculus Android Build

on:
  push:
    branches:
      - main  # Or the branch you want

jobs:
  build:
    runs-on: ubuntu-latest  # Uses GitHub's virtual machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Fetches your code

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # Recommended for Android
          java-version: 11

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: NavOculus-APK
          path: app/build/outputs/apk/debug/*.apk
