name: NavOculus Android Build

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  build:
    runs-on: ubuntu-latest  # Uses GitHub's virtual machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Clones your repository

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # Zulu OpenJDK
          java-version: 11

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2  # Sets up Android environment

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew  # Ensures Gradle is executable

      - name: Build APK
        run: ./gradlew assembleDebug  # Builds the debug APK

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: "NavOculus-APK"
          path: "app/build/outputs/apk/debug/app-debug.apk"  # Exact file path
